Repository Keerat666/Lumix, pull requests merged in 2024-10, with the labels that each got.

#75 Updated the footer
  ui/lumix/src/pages/contributors/index.js
  ui/lumix/src/pages/documentation/index.js
Labels: hacktoberfest-accepted

#77 Solved year issue now it will give current year
  package-lock.json
  package.json
  ui/lumix/src/pages/contributors/index.js
  ui/lumix/src/pages/documentation/index.js
Labels: good first issue, hacktoberfest-accepted

#69 Added Accordion Component
  ui/lumix/src/components/Accordion.jsx
  ui/lumix/src/pages/documentation/index.js
Labels: hacktoberfest-accepted

#80 Update the Lumix Documentation #78
  ui/lumix/README.md
Labels: documentation, good first issue, hacktoberfest-accepted

#79 Feat added: created hot-toast component
  package-lock.json
  package.json
  ui/lumix/src/components/CustomToast.js
  ui/lumix/src/index.js
  ui/lumix/src/pages/contributors/index.js
  ui/lumix/src/pages/documentation/index.js
Labels: hacktoberfest-accepted

#81 Added a new contributor
  ui/lumix/src/pages/contributors/index.js
Labels: hacktoberfest-accepted

#82 Added toast click to placeholder image
  ui/lumix/src/pages/documentation/index.js
Labels: hacktoberfest-accepted

#83 Deployment PR
  ui/lumix/build/asset-manifest.json
  ui/lumix/build/index.html
  ui/lumix/build/static/css/main.1a5434ef.css
  ui/lumix/build/static/css/main.1a5434ef.css.map
  ui/lumix/build/static/css/main.de4a85f1.css
  ui/lumix/build/static/css/main.de4a85f1.css.map
  ui/lumix/build/static/js/main.1cca162d.js
  ui/lumix/build/static/js/main.1cca162d.js.LICENSE.txt
  ui/lumix/build/static/js/main.9570ada8.js
  ui/lumix/build/static/js/main.9570ada8.js.LICENSE.txt
Labels: hacktoberfest-accepted
